const EVENT = {
    ALERT: 'ALERT',
    
    MODAL_OPEN: 'MODEL_OPEN',
    MODAL_CLOSE: 'MODEL_CLOSE',
    // Các event liên quan tới dữ liệu hiển thị
    RELOAD_LIST_ACCOUNT: 'RELOAD_LIST_ACCOUNT',
    RELOAD_LIST_ACCOUNT_GROUP: 'RELOAD_LIST_ACCOUNT_GROUP',
    RELOAD_LIST_SIP: 'RELOAD_LIST_SIP',
    RELOAD_LIST_QUEUE: 'RELOAD_LIST_QUEUE',
    RELOAD_LIST_PARTNER: 'RELOAD_LIST_PARTNER',
    RELOAD_LIST_CAMPAIGN: 'RELOAD_LIST_CAMPAIGN',
    RELOAD_FILE_STAT: 'RELOAD_FILE_STAT',
    RELOAD_LIST_FILE_CONTACT: 'RELOAD_LIST_FILE_CONTACT',
    RELOAD_LIST_CALL: 'RELOAD_LIST_CALL',

    RELOAD_LIST_CALL_GROUP_STATE: 'RELOAD_LIST_CALL_GROUP_STATE',
    RELOAD_LIST_CALL_STATE: 'RELOAD_LIST_CALL_STATE',
    RELOAD_LIST_CALL_BLACKLIST: 'RELOAD_LIST_CALL_BLACKLIST',
    RELOAD_LIST_CALL_SATISFACTION: 'RELOAD_LIST_CALL_SATISFACTION',
    RELOAD_LIST_CALL_STATUS: 'RELOAD_LIST_CALL_STATUS',
    RELOAD_LIST_CALL_STATUS_DETAIL: 'RELOAD_LIST_CALL_STATUS_DETAIL',
    RELOAD_LIST_CALL_CUSTOMER_GROUP: 'RELOAD_LIST_CALL_CUSTOMER_GROUP',
    RELOAD_LIST_CALL_TYPE: 'RELOAD_LIST_CALL_TYPE',
    RELOAD_LIST_CALL_REQUIRE: 'RELOAD_LIST_CALL_REQUIRE',
    RELOAD_LIST_CUSTOMER: 'RELOAD_LIST_CUSTOMER',
    RELOAD_LIST_OUTBOUND: 'RELOAD_LIST_OUTBOUND',
    RELOAD_LIST_INBOUND: 'RELOAD_LIST_INBOUND',
    RELOAD_LIST_LEAD: 'RELOAD_LIST_LEAD',
    // Các event liên quan tới api
    USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',

    USER_UPDATE_PASSWORD_SUCCESS: 'USER_UPDATE_PASSWORD_SUCCESS',
    USER_UPDATE_PASSWORD_FAILED: 'USER_UPDATE_PASSWORD_FAILED',
    
    USER_UPDATE_PROFILE_SUCCESS: 'USER_UPDATE_PROFILE_SUCCESS',
    USER_UPDATE_PROFILE_FAILED: 'USER_UPDATE_PROFILE_FAILED',


    // Các event liên quan tới socket
    INBOUND_STATUS: 'INBOUND_STATUS',
    BUSY_STATE: 'BUSY_STATE'
};

export default EVENT;